context:
  name: mergiraf
  version: "0.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://codeberg.org/mergiraf/mergiraf/archive/v${{ version }}.tar.gz
  sha256: fa46969f6215c9ab7078a3dec90d7b5976cf753f5f03f0f9a57b0f4e9ef541fa

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          # Needed to get tree-sitter to compile
          - export CFLAGS="${CFLAGS} -D_BSD_SOURCE"
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: mergiraf --help

about:
  homepage: https://mergiraf.org/
  summary: A syntax-aware git merge driver for a growing collection of programming languages and file formats.
  description: |
    Description of the package
  license: GPL-3.0-only
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  documentation: https://mergiraf.org/
  repository: https://codeberg.org/mergiraf/mergiraf

extra:
  recipe-maintainers:
    - Hofer-Julian
